Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 70

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/CaseEquality:
  Exclude:
    - 'lib/provider_dsl/record.rb'
    - 'lib/provider_dsl/zone.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/provider_dsl/gandi_proxy.rb'

Style/GuardClause:
  Exclude:
    - 'lib/provider_dsl/zone.rb'

Style/MethodMissing:
  Exclude:
    - 'lib/provider_dsl/gandi_proxy.rb'

Style/TrivialAccessors:
  Exclude:
    - 'lib/provider_dsl/zone.rb'

Style/MethodMissing:
  Exclude:
    - 'lib/provider_dsl/gandi_proxy.rb'
    - 'spec/provider_dsl/mocks/gandi_session.rb'
